# =============================================================================
# STAT DOCTOR - Flutter Application Configuration
# =============================================================================
# A comprehensive medical statistics and health management application built with Flutter
# Features: Medical statistics, health tracking, data visualization, patient management
# =============================================================================

name: stat_doctor
description: "A comprehensive medical statistics and health management Flutter application for tracking health metrics, analyzing medical data, and managing patient statistics."

publish_to: 'none'  # Private project - not published to pub.dev

version: 1.0.0+1  # Version 1.0.0, build number 1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # iOS-style icons for Cupertino widgets


  # =============================================================================
  # STATE MANAGEMENT & ARCHITECTURE
  # =============================================================================
  flutter_bloc: ^9.1.0  # BLoC pattern for predictable state management
  equatable: ^2.0.7     # Value equality for BLoC states and events
  dartz: ^0.10.1        # Functional programming utilities for error handling

  # =============================================================================
  # DEPENDENCY INJECTION
  # =============================================================================
  get_it: ^8.0.2        # Service locator for dependency injection and singleton management

  # =============================================================================
  # UI COMPONENTS & THEMING
  # =============================================================================
  adaptive_theme: ^3.6.0              # Dynamic dark/light theme switching
  flutter_screenutil: ^5.9.3          # Responsive UI scaling across devices
  flutter_animate: ^4.5.2             # Rich animation utilities and effects
  shimmer: ^3.0.0                     # Loading shimmer effects for better UX
  flutter_svg: ^2.0.16                # SVG vector graphics rendering
  cached_network_image: ^3.4.1        # Efficient cached network image loading
  be_widgets: ^1.0.2                  # Custom UI widget library
  timelines_plus: ^1.0.7              # Timeline widgets for booking history
  mobkit_dashed_border: ^0.0.7        # Dashed border widgets for forms

  # =============================================================================
  # FORM INPUT & VALIDATION
  # =============================================================================
  pin_code_fields: ^8.0.1             # OTP input fields for phone verification
  country_code_picker: ^3.1.0         # Country code picker for phone numbers
  country_picker: ^2.0.27             # Country selection widget
  phone_numbers_parser: ^9.0.3        # Phone number parsing and validation

  # =============================================================================
  # NETWORKING & API COMMUNICATION
  # =============================================================================
  dio: ^5.7.0                         # Advanced HTTP client for API calls
  pretty_dio_logger: ^1.4.0           # Request/response logging for debugging
  http_parser: ^4.1.2                 # HTTP parsing utilities

  # =============================================================================
  # LOCAL DATA STORAGE
  # =============================================================================
  hive: ^2.0.4                        # Lightweight NoSQL local database
  hive_flutter: ^1.1.0                # Flutter integration for Hive storage
  path_provider: ^2.1.5               # File system access for local storage
  path: ^1.9.0                        # Path manipulation utilities

  # =============================================================================
  # FILE & MEDIA HANDLING
  # =============================================================================
  flutter_image_compress: ^2.3.0      # Image compression for profile pictures
  image_picker: ^1.1.2                # Image selection from gallery/camera
  file_picker: ^10.2.0                # File selection for document uploads
  mime: ^2.0.0                        # MIME type detection for file handling
  open_file: ^3.5.10                  # File opening utilities

  # =============================================================================
  # UTILITIES & HELPERS
  # =============================================================================
  intl: ^0.20.2                       # Internationalization and localization
  haptic_feedback: ^0.5.1+1           # Haptic feedback for user interactions
  uuid: ^4.5.1                        # UUID generation for unique identifiers
  internet_connection_checker_plus: ^2.7.1  # Internet connectivity monitoring

  # =============================================================================
  # DEVELOPMENT & BUILD TOOLS
  # =============================================================================
  flutter_launcher_icons: ^0.14.3     # App icon generation for all platforms
  flutter_native_splash: ^2.4.4       # Splash screen generation
  permission_handler: ^12.0.0+1       # Runtime permission handling
  package_info_plus: ^9.0.0           # App package information access
  flutter_rating_bar: ^4.0.1          # Rating bar widget for reviews
  table_calendar: ^3.2.0


# =============================================================================
# DEVELOPMENT DEPENDENCIES
# =============================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter  # Flutter testing framework
  flutter_localizations:
    sdk: flutter  # Internationalization support
  flutter_lints: ^6.0.0  # Linting rules for code quality
  build_runner: ^2.1.2   # Code generation runner
  hive_generator: ^2.0.1 # Hive code generation for type adapters

# =============================================================================
# FLUTTER CONFIGURATION
# =============================================================================
flutter:
  uses-material-design: true  # Enable Material Design components
  generate: true             # Enable code generation for localization

  # =============================================================================
  # ASSET MANAGEMENT
  # =============================================================================
  assets:
    - assets/fonts/          # Custom font files (ReadexPro family)
    - assets/icons/          # SVG icons for UI components
    - assets/images/         # PNG/JPG images and logos
    - assets/translation/    # Localization files (ARB format)

  # =============================================================================
  # CUSTOM FONT CONFIGURATION
  # =============================================================================
  fonts:
    - family: HelveticaNeue  # Primary font family for the app
      fonts:
        - asset: assets/fonts/HelveticaNeueUltraLight.otf
          weight: 200  # Ultra light weight
        - asset: assets/fonts/HelveticaNeueThin.otf
          weight: 300  # Thin weight
        - asset: assets/fonts/HelveticaNeueLight.otf
          weight: 400  # Light weight
        - asset: assets/fonts/HelveticaNeueRoman.otf
          weight: 500  # Regular weight (default)
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 600  # Medium weight
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700  # Bold weight
        - asset: assets/fonts/HelveticaNeueHeavy.otf
          weight: 800  # Heavy weight
        - asset: assets/fonts/HelveticaNeueBlack.otf
          weight: 900  # Black weight

# =============================================================================
# APP ICON CONFIGURATION
# =============================================================================
flutter_launcher_icons:
  android: "ic_launcher"  # Android launcher icon name
  ios: true               # Generate iOS icons
  image_path: "assets/images/logo-mid.png"  # Source image (1024x1024px)
  adaptive_icon_background: "#0957DE"  # Android adaptive icon background
  adaptive_icon_foreground: "assets/images/logo-min.png"  # Foreground (432x432px)
  min_sdk_android: 21     # Minimum Android SDK version
  # remove_alpha_ios: true  # Remove alpha channel for iOS

# =============================================================================
# SPLASH SCREEN CONFIGURATION
# =============================================================================
flutter_native_splash:
  color: "#ffffff"  # Background color (white)
  image: assets/images/splash.png  # Splash screen image (1152x1152px)
  android_12:  # Android 12+ splash screen configuration
    image: assets/images/splash.png  # Android 12+ splash image
    icon_background_color: "#ffffff"   # Icon background color
    branding_mode: none  # No branding text overlay